set nocp
filetype plugin on
syntax enable
set number
set hls
set nobackup
set nowritebackup
set cindent
set ts=4
set softtabstop=4
set shiftwidth=4
"set textwidth=80
set expandtab
let g:load_doxygen_syntax=1
"au BufEnter *.cpp,*.cc,*.c set foldmethod=syntax "foldclose=all
autocmd InsertEnter * if !exists('w:last_fdm') | let w:last_fdm=&foldmethod | setlocal foldmethod=manual | endif
autocmd InsertLeave,WinLeave * if exists('w:last_fdm') | let &l:foldmethod=w:last_fdm | unlet w:last_fdm | endif
set cinoptions+=g0

"vtreeexplorer
let g:treeExplVertical=1
let g:treeExplDirSort=1
let g:treeExplWinSize=30

"minibufexpl
"let g:miniBufExplMapWindowNavVim = 1 
"let g:miniBufExplMapWindowNavArrows = 1 
"let g:miniBufExplMapCTabSwitchBufs = 1 
"let g:miniBufExplModSelTarget = 1 
"let g:miniBufExplForceSyntaxEnable = 1

set tags+=~/.vim/tags/stl

"OmniCppComplete
let OmniCpp_NamespaceSearch = 1
let OmniCpp_GlobalScopeSearch = 1
let OmniCpp_ShowAccess = 1
let OmniCpp_MayCompleteDot = 1
let OmniCpp_MayCompleteArrow = 1
let OmniCpp_MayCompleteScope = 1
let OmniCpp_DefaultNamespaces = ["std", "_GLIBCXX_STD"]
" automatically open and close the popup menu / preview window
au CursorMovedI,InsertLeave * if pumvisible() == 0|silent! pclose|endif
set completeopt=menuone,menu,longest,preview

"taglist
let Tlist_Use_Right_Window = 1

"Change to current working directory
"set autochdir
map <silent> ,cd :cd %:p:h<CR>

"To change width use 'vertical resize <size>' while in explorer window
map <silent> ,x :VSTreeExplore<CR>

"Make ctags
map <silent> ,ctl :!ctags -R --languages=c++,c --c++-kinds=+pl --fields=+iaS --extra=+q . <CR><CR>

"Tlist
map <silent> ,tt :TlistToggle<CR>
map <silent> ,tu :TlistUpdate<CR>

noremap <silent> ,zr :set foldlevel=3<CR>

map <silent> ,f :set foldmethod=syntax<CR>

noremap \c :s:^://:<CR>:nohls<CR>
noremap \u :s:^//::<CR>:nohls<CR>

set guifont=Courier\ 10\ Pitch\ 9
colorscheme desert

set guioptions-=T

set history=200
